CREATE TABLE IF NOT EXISTS employees
(id INTEGER NOT NULL AUTO_INCREMENT,
 first_name VARCHAR(55) NOT NULL,
 surname VARCHAR(55) NOT NULL,
 position VARCHAR(55) NOT NULL,
 phone VARCHAR(55) NOT NULL,
 PRIMARY KEY(id)
);